### ISSUE TITLE
時間計算有問題？

### ISSUE THREAD

**Issue by davidhcefx** [DeNT15T/Graduate_time_parser#2]
在 main.py [line 115](https://github.com/DeNT15T/Graduate_time_parser/blob/master/main.py#L115) 有以下code:

`calculate = int(grad_year) - int(enter_year)`

以清大為例，105 開頭的學號代表於 105 年入學，若是畢業年為 107，應該算是正常兩年畢業，但是 [line 122](https://github.com/DeNT15T/Graduate_time_parser/blob/master/main.py#L122) 卻會把它算為 2-3 年。

    elif calculate == 2:
            Y2_3 += 1

而若是 105 年入學，106 年畢業，應該算是一年提早畢業，但是 [line 119](https://github.com/DeNT15T/Graduate_time_parser/blob/master/main.py#L119) 卻會將之算為 2 年。

    elif calculate == 1:
            Y2 += 1

最後，`calculate == 0` 根本不會執行，因為實際上沒有人在入學的同一年畢業吧？

**Comment by davidhcefx** [comment]
### 其他計算方法

我發現有時候「畢業學年度」並不準，像是[這一則結果](https://etd.lib.nctu.edu.tw/cgi-bin/gs32/gsweb.cgi?o=dallcdr&s=id=%22G021050625150%22.&searchmode=basic)，畢業年度寫 106，但[實際上卻為 107](https://htchen.github.io/students.html)。
我目前猜測，或許用「出版年(民國)」會比較準一些，但這還有待驗證。

**Comment by DeNT15T** [comment]
你好，抱歉現在才注意到 issue

當初設計時主要是考量交大的制度，在交大畢業論文中，假設畢業學年度為 X 年，則實際畢業時間會落在 X/08 ~ (X+1)/07。

你的第一個例子中，有可能於 107 年 8 月準時畢業，也有可能延至 108 年 7 月才畢業，這個 range 很尷尬，因此分類至「2～3年畢業」這個較模糊的類別。

而第二個例子中，有可能於 106 年 8 月提早一年畢業，也有可能於 107 年 7 月準時畢業，因為重點在教授願意讓學生準時畢業，因此分類至「準時畢業」的類別。

若四間學校都沒有五年一貫的制度，`calculate == 0`的確應該不會執行，但由於我不清楚各學校關於這方面的規定，因此保留這段 code（若走五年一貫的方式，可能 105 年 9 月入學碩士班， 106 年 7月畢業，以交大規則來看就是 105 年入學年、 105 年畢業年）

若確定清大、中央、陽明的規則與上述的交大規則不同，我有空會再做修正，也歡迎自行修改。

選擇用畢業年計算而非出版年，是因為我不熟悉出版年的制度，不清楚「畢業」跟「出版」之間的時間差:sweat_smile:
